### ISSUE TITLE
Asset editor doesn't work properly when this package is installed

### ISSUE THREAD

**Issue by esdete2** [CarbonPackages/Carbon.Compression#7]
**Describe the bug**
The selection in the search dropdown of the asset editor is only applied at the second attempt. This error occurs only if this package is installed.

**To Reproduce**
1. install fresh Neos project with Neos.Demo data
2. install this package
3. add asset property to any component
```
    asset:
      type: 'Neos\Media\Domain\Model\Asset'
      ui:
        label: Asset
        inspector:
          group: general
```
4. in backend: use search function of asset editor to search for "cooking" and click on any result

**Expected behavior**
The option should be applied directly to the editor.

**Videos**
Without package:
https://user-images.githubusercontent.com/34043608/155683064-9b46dabe-ffa9-4c22-a35e-0ee56569cbe8.mov

With package installed:
https://user-images.githubusercontent.com/34043608/155683077-4bf87cea-9bf3-47de-8587-1b7d5ad3914b.mov
